# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
  paths:
    include:
      - 'result/*'

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '3b86b587-5b26-4381-870c-ce377136412c'
  imageRepository: 'demo'
  containerRegistry: 'votingapp.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/result/Dockerfile'
  tag: '$(Build.BuildId)'

pool:
 name: 'azurepool'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build

    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'buildAndPush'
        Dockerfile: 'result/Dockerfile'
        tags: '$(tag)'


- stage: Push
  displayName: push stage
  jobs:
  - job: Push
    displayName: Push

    steps:
    - task: Docker@2
      displayName: push an image to container registry
      inputs:
        containerRegistry: '$(dockerRegistryServiceConnection)'
        repository: '$(imageRepository)'
        command: 'push'
        tags: '$(tag)'